### ISSUE TITLE
What does "datetime" exactly mean?

### ISSUE THREAD

**Issue by HerbertLim** [socrata/discuss#101]
Hi, 
I found that if I query data at about 11:10 am, the "datetime" of the most recent data in the response is 10:00 am, "2019-12-26T10:00:00.000".

I would like to know exactly what the "datetime" means: the time of measuring or the time the data is published?

As far as I know, the air is measure for an hour and the average concentration of one hour is published in the next time. For example, the air is measure from 10:00~10:59, average concentration is calculated, and finally the measure is published at about 11:10. Which time does "datetime" in the response of API mean?

**Comment by znep** [comment]
Hi Herbert,

I don't know what dataset you are referring to, but the exact meaning of the data is something that only the dataset owner can answer as we host many datasets for many customers.  If you go to the dataset's landing page on the domain in question, you should find a button labelled "Contact Dataset Owner" which will let you ask them directly.

**Comment by HerbertLim** [comment]
Hi @znep 
I thought this issues is only for "Air Quality Monitoring Data". Thanks to you, I was able to find dataset owner and more documents. Thank you so much :)
