### ISSUE TITLE
App token not giving access to full dataset

### ISSUE THREAD

**Issue by abrown945** [socrata/discuss#104]
When I make a request with the app token I've been provided included as a parameter for the following [motor vehicle data](https://dev.socrata.com/foundry/data.cityofnewyork.us/h9gi-nx95), I am not given access to the full set of data as stated in the documentation.

I tried acquiring a new app token to see if it was the token I was initially provided, but I am still only getting the same random portion of the data in the form of an array of 1000 object values.

This is the exact same set of values that I receive if I make a request without the app token included.

I've been making an equivalent request with axios, but I've also tried the following format to no avail.

`https://data.seattle.gov/resource/3k2p-39jp.json?$$app_token=APP_TOKEN `

**Comment by znep** [comment]
Hi Avery,

Even with an app token, the default limit of 1000 results per page applies as per 
https://dev.socrata.com/docs/paging.html.  You can override it to a larger value by adding an explicit limit, for example  https://data.cityofnewyork.us/resource/h9gi-nx95.json?$$app_token=APP_TOKEN&$limit=10000

**Comment by abrown945** [comment]
Thank you
