### ISSUE TITLE
[www.datos.gov.co/gt2j-8ykr] Question about "Casos positivos de COVID-19 en Colombia"

### ISSUE THREAD

**Issue by nestorandrespe** [socrata/discuss#110]
API Docs: https://dev.socrata.com/foundry/www.datos.gov.co/gt2j-8ykr

The arguments limit and offset aren't working. I'm getting en error: Unrecognized arguments

**Comment by znep** [comment]
Hi @nestorandrespe ,

Can you give an example of a URL you are trying to use as a query?  Keep in mind those parameters need a `$` in front of them, which may need to be escaped depending how you are passing them to avoid being treated as variables.

**Comment by nestorandrespe** [comment]
you're right, I was missing the `$`
my bad...

**Comment by amaguilerac** [comment]
Hola, como puedo modificar la API para que me traiga la totalidad de los datos? Sólo me trae 1000 datos.

Gracias,

**Comment by znep** [comment]
@amaguilerac Please see https://dev.socrata.com/docs/paging.html ( https://translate.google.com/translate?hl=&sl=en&tl=es&u=https%3A%2F%2Fdev.socrata.com%2Fdocs%2Fpaging.html ).  We only have English documentation available I'm afraid, hopefully Google Translate can help.

Traducido por Google Translate:

Consulte https://dev.socrata.com/docs/paging.html (https://translate.google.com/translate?hl=&sl=en&tl=es&u=https%3A%2F%2Fdev.socrata.com% 2Fdocs% 2Fpaging.html). Me temo que solo tenemos documentación en inglés disponible, espero que Google Translate pueda ayudar.

**Comment by Romerolweb** [comment]
> Hola, como puedo modificar la API para que me traiga la totalidad de los datos? Sólo me trae 1000 datos.
> 
> Gracias,

Hi @amaguilerac, I highly recommend you to create an App token, it works for me. Have a good day.

**Comment by 1cgonza** [comment]
Hi, is there any way to access metadata of the dataset? for instance, total number of entries or last date it was updated? 
The number of entries is useful for a pagination interface with multiple pages already in display. 
The last date it was updated is to check if I need to make a roundtrip to the API or used a cached version of the data. 

Thanks!
