### ISSUE TITLE
How to pull all rows

### ISSUE THREAD

**Issue by Jacyle** [socrata/discuss#112]
I'm using the following python code provided on the webpage:

[https://dev.socrata.com/foundry/data.medicaid.gov/rt4v-78r4](url)

I removed 'limit' from client.get(), but only receive 1000 rows. I also created an App Token and it doesn't seem to make a difference. Please advise.

`import pandas as pd
from sodapy import Socrata

# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
client = Socrata("data.medicaid.gov", None)

# Example authenticated client (needed for non-public datasets):
# client = Socrata(data.medicaid.gov,
#                  MyAppToken,
#                  userame="user@example.com",
#                  password="AFakePassword")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("rt4v-78r4", limit=2000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)`

**Comment by znep** [comment]
As documented at https://dev.socrata.com/docs/queries/limit.html the default limit if none is specified is 1000.  If you wish to pull all the records in one API call, you will need to specify a limit that is larger than the size of the dataset, eg. 100000.

**Comment by Jacyle** [comment]
When I specify limit = 1000000 (because there's 8M+ records) I get a ReadTimeout error:

HTTPSConnectionPool(host='data.medicaid.gov'), port=443): Read timed out. (read timeout=10)

**Comment by znep** [comment]
You will need to configure your code to use a larger timeout by passing in a timeout setting when creating the client, eg. `timeout=120`.  You also will want to be sure to modify the code so you download the data and access it locally so you aren't constantly re-querying it as it is a large amount of data.  

Depending on your available resources you may run into local memory or other constraints attempting to process large datasets, that can require specialized expertise that we are not able to assist with on an individual basis.

**Comment by Jacyle** [comment]
increasing the timeout worked, thanks!
