### ISSUE TITLE
How to use filters in the API

### ISSUE THREAD

**Issue by gmalekar** [socrata/discuss#113]
I am using python pandas and I am trying to filter the response by expirationdate.

url = ("https://data.cityofchicago.org/resource/r5kz-chrr.json?$where=expiration_date>2020-01-01T00:00:00")

error message
{'code': 'query.compiler.malformed',
 'error': True,
 'message': 'Could not parse SoQL query "select * where expiration_date>2020-01-01T00:00:00" at line 1 character 42',
 'data': {'query': 'select * where expiration_date>2020-01-01T00:00:00',
  'position': {}}}

**Comment by znep** [comment]
You need to enclose the date in single quotes, eg. ```https://data.cityofchicago.org/resource/r5kz-chrr.json?$where=expiration_date>'2020-01-01T00:00:00'```

**Comment by gmalekar** [comment]
Thank you 🙏

**Comment by gmalekar** [comment]
Thank you for the reply however how do I add limit to the query
"https://data.cityofchicago.org/resource/r5kz-chrr.json?$where=expiration_date>'2020-01-01T00:00:00'?$limit=1000000

**Comment by znep** [comment]
Query parameters are separated with `&`s as per normal HTTP query string conventions, eg. https://data.cityofchicago.org/resource/r5kz-chrr.json?$where=expiration_date%3E%272020-01-01T00:00:00%27&$limit=1000000
