### ISSUE TITLE
Need public notification of upcoming field changes

### ISSUE THREAD

**Issue by freilich** [socrata/discuss#115]
[www.dallasopendata.com/9fxf-t2tr] On May 14, 2020 the date_time field was removed from this feed without any notice.  This broke things downstream until we could switch to the separate date and time fields.  Let's get a blog or something set up so we have notification of upcoming changes.

**Comment by znep** [comment]
Hi there,

Socrata does not control the contents of individual datasets, that is up to the dataset publisher.  You can reach out to the dataset owner using the "Contact Dataset Owner" button on https://www.dallasopendata.com/Public-Safety/Dallas-Police-Active-Calls/9fxf-t2tr
