### ISSUE TITLE
[health.data.ny.gov/xdss-u53e] Question about "New York State Statewide COVID-19 Testing"

### ISSUE THREAD

**Issue by mattlgardner** [socrata/discuss#118]
API Docs: https://dev.socrata.com/foundry/health.data.ny.gov/xdss-u53e

Hi there,

Is anyone else using this data? I have been trying to reference the data set at these links:

https://health.data.ny.gov/resource/xdss-u53e.csv
https://health.data.ny.gov/resource/xdss-u53e.json

But it seems that the data stops at "Chemung" and doesn't include any other counties on from that - this also seems to be at about 1000 lines.

Does anyone know what might be happening here?

Thanks,
M

**Comment by znep** [comment]
Hi,

Please see https://dev.socrata.com/docs/paging.html#2.1 the default limit is 1000 records, you need to specify a larger `$limit` parameter (you can set that as large as your code can handle) and/or page through the data using `$offset`.  

- Marc
