### ISSUE TITLE
Question 2 about "New York State Statewide COVID-19 Testing

### ISSUE THREAD

**Issue by SnowinNY** [socrata/discuss#119]
I have also been encountering the 1000 record limit on the https://health.data.ny.gov/resource/xdss-u53e.csv.  I have been playing with the limit and offset query options for a while and all I get is an error or empty file back.  I want to download the entire file at once so I have tried variations on the following and nothing works:

https://health.data.ny.gov/resource/xdss-y53e.csv?limit=100000&limit=100000&limit=100000&offset=0

I finally resorted to using:

https://health.data.ny.gov/api/views/xdss-u53e/rows.csv 

This does pull all the rows down but I don't know how stable this will be going forward vs the resource reference.  Can you look at the first url and modify it if it is incorrect for me?

Thanks,

**Comment by znep** [comment]
You are missing the `$` sign in your URL (and also have a typo in the resource identifier, it should be `xdss-u53e` not `xdss-y53e`).  eg. https://health.data.ny.gov/resource/xdss-u53e.csv?$limit=100000

If you just want to export the data the second URL you reference is also find to use, it doesn't have the full querying capabilities of the resource endpoint.

**Comment by SnowinNY** [comment]
It didn't like that.  Error back is unrecognized arguments.

https://health.data.ny.gov/resource/xdss-u53e.csv?$limit=500000

{
  "error" : true,
  "message" : "Unrecognized arguments []"
}
~
