### ISSUE TITLE
NYC Eviction data has a Year 2070 for executed_date field 

### ISSUE THREAD

**Issue by johnneto2020** [socrata/discuss#120]
Please check the executed_date field for the Eviction data set. Link: https://data.cityofnewyork.us/City-Government/Evictions/6z8x-wfk4

**Comment by znep** [comment]
Hi there,

Sorry for the delayed response.  Socrata does not control the contents of data published by our customers.  You can contact the NYC Open Data team at https://opendata.cityofnewyork.us/engage/ and they may be able to help you.

Thanks,

Marc
