### ISSUE TITLE
Address data in Orpin Contracts Report

### ISSUE THREAD

**Issue by stevecdr** [socrata/discuss#122]
The address data in the Oregon ORPIN contracts report file pertain to contractors' addresses, not to construction project addresses.  Contractors' addresses can be found by other means, but most interest in construction projects centers around the construction sites.  (Of course, not every project has a "site", as in the case of jobs like highway paving and "all DOT offices around the state".  Such projects could have an address such as "various" or "state-wide".)

What are the prospects and/or procedures to revise the report?

The referenced report is here:  https://dev.socrata.com/foundry/data.oregon.gov/6e9e-sfc4

Thanks, Steve

**Comment by znep** [comment]
Hi Steve,

You can contact the dataset owner by following the "Contact Dataset Owner" link from https://data.oregon.gov/Revenue-Expense/ORPIN-Contracts-Report-FY-2019-2012-Composite/6e9e-sfc4 

Socrata doesn't have any control over the content of the datasets hosted on our platform.

Thanks,

Marc

**Comment by stevecdr** [comment]
Thanks!


Steve
