### ISSUE TITLE
Are NA/null values coded as zero?

### ISSUE THREAD

**Issue by saveyak** [socrata/discuss#150]
I've noticed that there are many counties in Nebraska that say that the partial vaccination rate is 0, but do have a number for the full (both doses) vaccination rate. On the CDC website, these values are listed as N/A (see https://covid.cdc.gov/covid-data-tracker/#county-view). Am I correct to assume that 0 values in the data are actually null/NA values?

**Comment by znep** [comment]
Hi there,

Socrata does not control the contents of datsets on our platform.  If you are referencing a dataset hosted on our platform, you will need to contact the dataset owner.  Depending on their configuration, there may be a contact dataset owner button available.

Thanks,

Marc
