### ISSUE TITLE
[opendata.rdw.nl/m9d7-ebf2] Question about "Open Data RDW: Gekentekende_voertuigen"

### ISSUE THREAD

**Issue by jeffreyvdhondel** [socrata/discuss#160]
API Docs: https://dev.socrata.com/foundry/opendata.rdw.nl/m9d7-ebf2

The dataset returns with 0 rows do you know what happend.

**Comment by KrakeWHM** [comment]
Experiencing the same issues, hope to get an update soon.

**Comment by dsmink** [comment]
Same here... 200 response with emtpy set of data.

**Comment by KrakeWHM** [comment]
Issues have been resolved as far as I can see..

**Comment by jeffreyvdhondel** [comment]
Yes i has been resolved.

**Comment by dsmink** [comment]
@jeffreyvdhondel,
Maintenance they called it... I have my thoughts...
