### ISSUE TITLE
[data.sfgov.org/yhqp-riqs] Question about "Street Sweeping Schedule"

### ISSUE THREAD

**Issue by gilles-yvetot** [socrata/discuss#164]
API Docs: https://dev.socrata.com/foundry/data.sfgov.org/yhqp-riqs

I am trying to use the street sweeping schedule API but it looks like they are duplicates:
```javascript
[{
    cnn: '3442000',
    corridor: 'Bush St',
    limits: 'Hyde St  -  Larkin St',
    cnnrightleft: 'R',
    blockside: 'North',
    fullname: 'Monday',
    weekday: 'Mon',
    fromhour: '7',
    tohour: '9',
    week1: '1',
    week2: '1',
    week3: '1',
    week4: '1',
    week5: '1',
    holidays: '0',
    blocksweepid: '1629330',
    line: { type: 'LineString', coordinates: [Array] }
  },
 {
    cnn: '3442000',
    corridor: 'Bush St',
    limits: 'Hyde St  -  Larkin St',
    cnnrightleft: 'R',
    blockside: 'North',
    fullname: 'Friday',
    weekday: 'Fri',
    fromhour: '7',
    tohour: '9',
    week1: '1',
    week2: '1',
    week3: '1',
    week4: '1',
    week5: '1',
    holidays: '0',
    blocksweepid: '1629349',
    line: { type: 'LineString', coordinates: [Array] }
  }
]
```
Maybe there is something I am not understanding here. Both items are for the same street, same side of the sidewalk but they have different times.

**Comment by bungee1980** [comment]
one is for friday one is for monday. so on that section of bush st. its monday and friday 7-9. although for that street heading into downtown, it is probably every day. check to see if there are other objects for the other weekdays.

**Comment by gilles-yvetot** [comment]
@bungee1980 thanks a lot! I didn't realize it was twice a day, the sign in the street only say Monday though

**Comment by bungee1980** [comment]
it isn't twice a day. its a range. from 7am - 9am on monday there is no parking because of street sweeping. the same thing on friday, no parking 7-9 due to streetsweeping.
you can get the json by the cnn value and it gives 3 blocksweepids:

`curl https://data.sfgov.org/resource/yhqp-riqs.json?cnn=3442000
[
  {
    "cnn": "3442000",
    "corridor": "Bush St",
    "limits": "Hyde St  -  Larkin St",
    "cnnrightleft": "L",
    "blockside": "South",
    "fullname": "Wednesday",
    "weekday": "Wed",
    "fromhour": "6",
    "tohour": "8",
    "week1": "1",
    "week2": "1",
    "week3": "1",
    "week4": "1",
    "week5": "1",
    "holidays": "0",
    "blocksweepid": "1629314",
    "line": {
      "type": "LineString",
      "coordinates": [
        [
          -122.417016878024,
          37.789110175732
        ],
        [
          -122.418655872543,
          37.788909612202
        ]
      ]
    }
  },
  {
    "cnn": "3442000",
    "corridor": "Bush St",
    "limits": "Hyde St  -  Larkin St",
    "cnnrightleft": "R",
    "blockside": "North",
    "fullname": "Friday",
    "weekday": "Fri",
    "fromhour": "7",
    "tohour": "9",
    "week1": "1",
    "week2": "1",
    "week3": "1",
    "week4": "1",
    "week5": "1",
    "holidays": "0",
    "blocksweepid": "1629349",
    "line": {
      "type": "LineString",
      "coordinates": [
        [
          -122.417016878024,
          37.789110175732
        ],
        [
          -122.418655872543,
          37.788909612202
        ]
      ]
    }
  },
  {
    "cnn": "3442000",
    "corridor": "Bush St",
    "limits": "Hyde St  -  Larkin St",
    "cnnrightleft": "R",
    "blockside": "North",
    "fullname": "Monday",
    "weekday": "Mon",
    "fromhour": "7",
    "tohour": "9",
    "week1": "1",
    "week2": "1",
    "week3": "1",
    "week4": "1",
    "week5": "1",
    "holidays": "0",
    "blocksweepid": "1629330",
    "line": {
      "type": "LineString",
      "coordinates": [
        [
          -122.417016878024,
          37.789110175732
        ],
        [
          -122.418655872543,
          37.788909612202
        ]
      ]
    }
  }
]
`
this is showing that there is street cleaning mondays and fridays from 7am to 9am on the north side of the street. AND there is also street cleaning on the south side on wednesdays only from 6am to 8am (i actually walked down there to take a look lol. i swear the sign said 6am to 7am). just starting to play with this data myself so interested in any other questions...

**Comment by gilles-yvetot** [comment]
I do have an extra question though.
I am trying to use `intersects` in the following query:
`https://data.sfgov.org/resource/yhqp-riqs.json?$where=intersects(line,'POLYGON((-122.41858210407510.000036145352960198836 37.788811859739610.000036000036000036, -122.41861824942806 37.788811859739610.000036000036000036, -122.41861824942806 37.78877585970361, -122.41858210407510.000036145352960198836 37.78877585970361))')` 
and I got the following error:

```
Query coordinator error: query.soql.type-mismatch; Type mismatch for intersects, is text; position: Map(row -> 1, column -> 216, line -> \"SELECT `cnn`, `corridor`, `limits`, `cnnrightleft`, `blockside`, `fullname`, `weekday`, `fromhour`, `tohour`, `week1`, `week2`, `week3`, `week4`, `week5`, `holidays`, `blocksweepid`, `line` WHERE intersects(`line`, 'POLYGON((-122.41858210407510.000036145352960198836 37.788811859739610.000036000036000036, -122.41861824942806 37.788811859739610.000036000036000036, -122.41861824942806 37.78877585970361, -122.41858210407510.000036145352960198836 37.78877585970361))')\\n
```

From the documentation you need to specify the field `line` as the first parameter then a polygon so I am not sure where is the type mismatch
