### ISSUE TITLE
[data.seattle.gov/vwtx-gvpm] Question about "Trails"

### ISSUE THREAD

**Issue by EricMentele** [socrata/discuss#18]
API Docs: https://dev.socrata.com/foundry/data.seattle.gov/vwtx-gvpm What is "check steps" type of "surface_ty"? Does this mean rough terrain? I'm marking surface types in Seattle Trails App by soft, medium, hard and stairs groupings.

**Comment by EricMentele** [comment]
@chrismetcalf

**Comment by chrismetcalf** [comment]
@EricMentele I'll see if I can get somebody at the city to take a look! 🌲 🌇

**Comment by chrismetcalf** [comment]
@EricMentele Took awhile, but I got an answer from the city that (I hope) should help:

> "Check step" - Its when there are several check steps installed in a short period. Usually on a slope that is not steep enough for box steps but steep enough to need something. If there are several installed then we have identified that section trail type. If there is just one step or 2 then it would be a point.
