### ISSUE TITLE
[data.montgomerycountymd.gov/yc8a-5df8] Question about Montgomery County, MD Crime API

### ISSUE THREAD

**Issue by rdeprey** [socrata/discuss#21]
I was reviewing the API Docs located here, https://dev.socrata.com/foundry/data.montgomerycountymd.gov/yc8a-5df8, and noticed that the data in the API doesn't seem to accurately reflect the data in the Montgomery County Crime Open Data Portal, https://data.montgomerycountymd.gov/Public-Safety/Crime/icn6-v9z3.  How often is the API data reviewed?

**Comment by marks** [comment]
The data in the API is kept in sync with the dataset in near real time and shouldn't lag more than an hour or two at the most. 

To help us troubleshoot and get to the bottom of this, can you point out a specific difference you are seeing?

Best,

Mark

**Comment by rdeprey** [comment]
Sorry for my delayed reply, Mark.  I noticed that in the open data portal provided by Montgomery County, https://data.montgomerycountymd.gov/Public-Safety/Crime/icn6-v9z3, there are quite a few crimes listed from this month, but none of them appear in the API here, https://data.montgomerycountymd.gov/resource/yc8a-5df8.json.

Best,
Rebecca

**Comment by marks** [comment]
@rdeprey np. Specific examples would be helpful but I am having our customer support and engineering teams take a look at this in parallel.

**Comment by rdeprey** [comment]
Thank you!  Here are screenshots of a few specific records that I didn't see in the API feed:

![screen shot 2016-05-30 at 8 39 46 am](https://cloud.githubusercontent.com/assets/453900/15649798/30b90f34-2642-11e6-9616-d28e1e6ae169.png)

----------------------------------------

![screen shot 2016-05-30 at 8 40 58 am](https://cloud.githubusercontent.com/assets/453900/15649807/41bb92e8-2642-11e6-9718-8ead5f4e73ec.png)

----------------------------------------

![screen shot 2016-05-30 at 8 44 25 am](https://cloud.githubusercontent.com/assets/453900/15649865/baa9ef88-2642-11e6-8c49-1182a2b09a5a.png)

**Comment by marks** [comment]
@rdeprey this is helpful -- for the time being, you can use the API at https://data.montgomerycountymd.gov/resource/icn6-v9z3.json (for example, https://data.montgomerycountymd.gov/resource/icn6-v9z3.json?incident_id=201081452?incident_id=201081452 works)

This older API, for this specific dataset, seems to be more accurate and you can read more about the new vs old APIs at https://dev.socrata.com/changelog/2015/04/27/new-higher-performance-apis.html

Sorry for any inconvenience. We will follow up when we have more information and, of course, a fix.

**Comment by marks** [comment]
Hey @rdeprey - this should be resolved now. It appears to have been a one-off issue that has been fixed on the Socrata side. Mark

**Comment by rdeprey** [comment]
Thanks @marks! :)
