### ISSUE TITLE
[data.nashville.gov/xbru-cfzi] Question about "Parks Locations - Official"

### ISSUE THREAD

**Issue by danparker-nsite** [socrata/discuss#22]
API Docs: https://dev.socrata.com/foundry/data.nashville.gov/xbru-cfzi

The mapped_location_zip data seems to be blank in the Parks Locations resource. Am I missing something? I'd like to get a lat/lon or zip code to associate with the park data.

Thanks in advance!

**Comment by marks** [comment]
Hi @danparker-nsite - it looks like this dataset does not have lat/long or zip codes. I am not sure if it is a data publisher or Socrata error but I am putting in a ticket to have a Socrata team member look into it ASAP. Standby while I see if I can create a copy of this dataset that is properly geocoded for ya...

**Comment by marks** [comment]
@danparker-nsite can you please try https://dev.socrata.com/foundry/communities.socrata.com/wntx-qssu ? This is a copy of the dataset that I made and forced it to geocode from address to lat/long.

For example, here is the API call for GeoJSON for all 123 parks: `https://communities.socrata.com/resource/wntx-qssu.geojson?$limit=123`

**Comment by danparker-nsite** [comment]
Awesome, thanks for the quick conversion to lat/lon for me. I'll close this ticket since you opened another one to look into the zip code issue. Much appreciated! (Mental note for myself to look into geocoding, that was impressive)
