### ISSUE TITLE
[data.oregon.gov/qajw-6p2c] Question about "New Businesses Registered Last Month"

### ISSUE THREAD

**Issue by marfi** [socrata/discuss#24]
Does https://dev.socrata.com/foundry/data.oregon.gov/qajw-6p2c always returns results for the previous month?

If so: https://data.oregon.gov/api/views/esjy-u4fc/ seems to return data for May/16.

Can I get a list for all months?

**Comment by chrismetcalf** [comment]
@marfi It does look like it only contains the last month's worth of business registrations. This SoQL query confirms that: 

https://data.oregon.gov/resource/qajw-6p2c.json?%24select=min%28registry_date%29%2C%20max%28registry_date%29

It's a bit awkward to access, but it does look like they have a number of trailing months available as additional datasets: https://data.oregon.gov/browse?limitTo=datasets&utf8=%E2%9C%93&q=new%20business&sortBy=relevance

**Comment by marfi** [comment]
@chrismetcalf  Thank you very much for pointing me how to access the historical!

**Comment by chrismetcalf** [comment]
No problem @marfi! I'll close this issue then!
