### ISSUE TITLE
[data.seattle.gov/kzjm-xkqj] Missing "state", "level", and "units" fields

### ISSUE THREAD

**Issue by Knetic** [socrata/discuss#28]
The endpoint for the [realtime 9/11 fire calls](https://dev.socrata.com/foundry/data.seattle.gov/kzjm-xkqj) data doesn't expose information about whether or not the call is active or closed. However, the much-more-primitive site (hosted by city of seattle) [located here](http://www2.seattle.gov/fire/realtime911/getRecsForDatePub.asp?action=Today&incDate=&rad1=des) indicates which units are/were dispatched, the state of the call, and the level.

Not sure this is the right place for feature requests like this, but I figure if anyone can has the right points of contact to feed this back to the city of seattle, they'd be here.

**Comment by chrismetcalf** [comment]
Thanks @Knetic! I'll pass this on to the team at the City of Seattle. I don't think they have an active GitHub account yet, but I can pass the message on to them and let you know what they say.

**Comment by chrismetcalf** [comment]
@Knetic Can you reach out to the city at open.data@seattle.gov? They should be able to help you out via that email address.

**Comment by Knetic** [comment]
Sounds good, thanks!
