### ISSUE TITLE
["https://data.brla.gov/resource/6afw-h38f.json?naicgroupname=HEALTH CARE & SOCIAL ASSISTANCE (I)"] search query not working?

### ISSUE THREAD

**Issue by danrock111** [socrata/discuss#39]
The search query for [?naicgroupname=HEALTH CARE & SOCIAL ASSISTANCE (I)] is not working, but most other search queries do work such as RETAIL TRADE (G). Please help?

**Comment by danrock111** [comment]
Thank you @chrismetcalf! You are a lifesaver. Wow, it was such a dumb mistake. lol

**Comment by chrismetcalf** [comment]
No problem, glad that worked!
