### ISSUE TITLE
[https://dev.socrata.com/foundry/data.cms.gov/iadr-zq3i]

### ISSUE THREAD

**Issue by dnolasco** [socrata/discuss#41]
Hi,

I am getting an error when invoking: https://data.cms.gov/resource/iadr-zq3i.json

Can you please let me know why this error occurs? This used to work from our app and recently discovered that it has stopped. This time I am passing an APP TOKEN, but still getting the error below:

"The underlying connection was closed: An unexpected error occurred on a send."

Thanks.

**Comment by chrismetcalf** [comment]
It sounds like what you're encountering is related to our [recent change that disables TLS 1.0 as a supported protocol for HTTPS connections](https://dev.socrata.com/changelog/2016/11/29/import-tls-security-upgrade.html).

What programming language and compiler or interpreter are you using? How you enable TLS 1.1 or 1.2 differs depending on what platform you're on.

**Comment by dnolasco** [comment]
Currently using .net with RestSharp library. I tested using WebClient but got the same issue. If there's no current solution I might just request this url from javascript?

**Comment by chrismetcalf** [comment]
In .NET, you just need to set up the `SecurityProtocol` framework to enable only TLS 1.1+. There are details of how to do so in this issue: https://github.com/CityofSantaMonica/SODA.NET/issues/65

**Comment by dnolasco** [comment]
Thanks a bunch!
