### ISSUE TITLE
Dataset 'a9we-mtpn' was not found

### ISSUE THREAD

**Issue by djds23** [socrata/discuss#47]
I was trying to fetch `a9we-mtpn` from the SODA api, but I get back this error message:

```JSON
{
  "message": "Dataset '_a9we-mtpn' was not found",
  "errorCode": "soda.dataset.not-found",
  "data": {
    "dataset": "_a9we-mtpn"
  }
}
```

I believe it is an issue on your side because even when I visit the dataset here:

https://dev.socrata.com/foundry/data.cityofnewyork.us/a9we-mtpn

and I use `try it`, I get the following issue on safari:

![screen shot 2017-03-14 at 10 25 59 pm](https://cloud.githubusercontent.com/assets/5833968/23930938/ca84f87a-0905-11e7-8589-5caac663582a.png)

I tried the same setup in chrome and it also broke.

Trying to hit the url directly here also did not work:

<img width="969" alt="fetch dataset issues" src="https://cloud.githubusercontent.com/assets/5833968/23930953/d626ca50-0905-11e7-8daa-b1fd4b48ea05.png">

Thanks for your time,
Dean

**Comment by djds23** [comment]
The issue here is that I was looking at the wrong endpoint. The proper endpoint can be found under, Export > SODA API > API Endpoint:

<img width="952" alt="screen shot 2017-03-15 at 10 22 06 am" src="https://cloud.githubusercontent.com/assets/5833968/23952899/59409d0e-0969-11e7-9a11-7e44442899a4.png">

**Comment by chrismetcalf** [comment]
@djds23 Glad you were able to figure out what was going on. How did find your way to ythe original URL, the one for `a9we-mtpn`? I'd like to prevent others from ending up at that dead end

**Comment by djds23** [comment]
@chrismetcalf to be honest I'm not sure where I found the original socrates link above, but I think I just took the ID from the url in the NYC repository:

https://data.cityofnewyork.us/Social-Services/NYC-Wi-Fi-Hotspot-Locations/a9we-mtpn

If I had followed the proper path and pressed the api buttons on the page, it would have taken me to the proper page:

https://dev.socrata.com/foundry/data.cityofnewyork.us/jd4g-ks2z

**Comment by chrismetcalf** [comment]
@djds23 Aha! Ok that makes sense. Those API-specific documentation pages are automatically generated, and although the template is pretty smart, I never taught it anything interesting to do with maps like `a9we-mtpn`.

Been meaning to do something about that for awhile, but as there shouldn't be any way to get there without hand-coding a URL, it hasn't been high priority: https://github.com/socrata/dev.socrata.com/issues/475
