### ISSUE TITLE
C# and pwoershell gets error's TLS 1.2

### ISSUE THREAD

**Issue by Opvolger** [socrata/discuss#48]
Invoke-RestMethod : The underlying connection was closed: An unexpected error occurred on a send

I have used the example:
`$url = "https://opendata.rdw.nl/resource/m9d7-ebf2"
$apptoken = "YOURAPPTOKENHERE"

# Set header to accept JSON
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Accept","application/json")
$headers.Add("X-App-Token",$apptoken)

$results = Invoke-RestMethod -Uri $url -Method get -Headers $headers`

I had to add:
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

can this by added by the example(s)

**Comment by chrismetcalf** [comment]
@Opvolger Thanks for the tip! I'll add this to the PowerShell snippet, as suggested! 🍺
