### ISSUE TITLE
[data.cityofnewyork.us/ujkp-2x99] Question about "Benefits and Programs API"

### ISSUE THREAD

**Issue by benefitkitchen** [socrata/discuss#49]
API Docs: https://dev.socrata.com/foundry/data.cityofnewyork.us/ujkp-2x99

Please consider sending the data results without any HTML formatting. I'd love to be able to use the JSON file to make links to the appropriate forms for specific programs, but I will have to use JS to "deformat" the content before I use it in the page. 

If the JSON file came with no formatting, I could use it as I wish and apply my own formatting to the result.

**Comment by benefitkitchen** [comment]
I'm getting all results in triplicate. If I view the complete dataset (https://data.cityofnewyork.us/resource/ujkp-2x99.json) and then search "if you have a disability that makes it hard to use" it is clear that I'm getting the Access-A-Ride data three times. (All other data are repeated three times throughout the JSON file).

**Comment by chrismetcalf** [comment]
@benefitkitchen I did some digging, and it looks like the embedded HTML tags and duplicated records are part of the source dataset published by the city. I can give you some advice about how to use SoQL queries to filter some of the duplication out, but ultimately the city will need to fix their data loading process to make sure the duplication and tags are removed.

They're usually pretty responsive, have you tried contacting them through their [contact us](http://opendata.cityofnewyork.us/engage/) form?

**Comment by benefitkitchen** [comment]
Thanks Chris

I'll follow up with the city.

Thanks for the quick reply,
Dan



-------------
