### ISSUE TITLE
Getting Council Agenda data into Open Data Portal

### ISSUE THREAD

**Issue by rskoenig** [socrata/discuss#50]
Hi there, we're developing an Open City Council [app](https://github.com/civinomics/city-council) that leverages your open data platform.

The City of Austin has a feed of their Council Agenda Items on their feed:
https://data.austintexas.gov/Government/Austin-City-Council-Agenda-Items/es7e-878h

But the City of Las Vegas does not:
https://opendata.lasvegasnevada.gov/browse?q=council&sortBy=relevance&utf8=%E2%9C%93

Both use the same SIRE agenda management system. Is there a way for Las Vegas to get its Agenda Item data from SIRE into Socrata Open Data?

**Comment by chrismetcalf** [comment]
@rskoenig We sure can try! I'll let our account manager know there's interest, and we'll see if they can drum up interest from the city.

What's your use case for the data? Knowing what people want to build (and thus what benefits citizens might get) helps make a case for releasing new datasets.

**Comment by rskoenig** [comment]
Use case is making these agendas interactive so Citizens van vote and comment on agenda items.

Does a city have to pay to integrate new data into its Open Data portal?
I'm in touch with the City of Las Vegas as well and can certainly encourage them to take any necessary steps.

**Comment by chrismetcalf** [comment]
Want to email me and I can connect you up with our team? 

`chris.metcalf at $thatcompanyiworkfor.com`
