### ISSUE TITLE
Where's the updated 'Array of things' information?

### ISSUE THREAD

**Issue by alxfed** [socrata/discuss#61]
On their website (http://arrayofthings.github.io/) there is a promise to make it available "...early in 2017",
on this page: https://dev.socrata.com/foundry/data.cityofchicago.org/dbwu-caep there is a funny phrase that the copy of data "... was last synchronized at 6/14/2017, 10:18:23 AM, and is currently **up to date**." :)

It was September 5 last time I checked. :)

Regards,

Alex Fedotov

**Comment by chrismetcalf** [comment]
@alxfed The irony of me taking 3 months to reply to you is not lost to me, but I'd suggest using the "Contact Us" link in the footer of https://data.cityofchicago.org/. That'll get to the right people at the city, and they hopefully will be able to prioritize posting that dataset.

**Comment by alxfed** [comment]
@chrismetcalf Thank you. Irony returned (today is Feb 19 :) ). I believe we could do this over the snail mail... like, with REAL snails. :)
