### ISSUE TITLE
Parking Regulation [New York] 500 error

### ISSUE THREAD

**Issue by Frenks** [socrata/discuss#62]
Hello!

Wanted to report that api endpoint : https://data.cityofnewyork.us/resource/xswq-wnv9.json is returning error nr. 500. 

From here : https://dev.socrata.com/foundry/data.cityofnewyork.us/xswq-wnv9

What could be the issue? Thank you very much!!

**Comment by chrismetcalf** [comment]
Looks like this has since cleared itself up, closing this ticket
