### ISSUE TITLE
[data.seattle.gov/vwtx-gvpm] Question about "Trails"

### ISSUE THREAD

**Issue by EricMentele** [socrata/discuss#9]
API Docs: https://dev.socrata.com/foundry/data.seattle.gov/vwtx-gvpm How should the "trail_clas" number be used? If I want to fetch only officially endorsed trails, which numbers are they?

**Comment by chrismetcalf** [comment]
Thanks! I've reached out to the data owner and hopefully we should hear
back soon.

**Comment by SeattleParks** [comment]
Hi Eric, 0=Unverified, 1=Verified They are both officially endorsed trails that have been known for years. The distinction is the Trails crew has been out recently to visit the Verified trails. Thanks for your interest. Hope this helps! Chris Smith

**Comment by EricMentele** [comment]
Hi Chris,

This definitely helps. Thanks!

Best,

Eric

**Comment by chrismetcalf** [comment]
Thanks @SeattleParks! :evergreen_tree:
